[package]
name = "udf_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
curl = "0.4.44"
udf = "0.4.5"

[package.metadata.release]
shared-version = true
